### ISSUE TITLE
Retrieving information of <Problem> section in tasks. 

### ISSUE THREAD

**Issue by hasanbaig** [copasi/basico#12]
Hi, 

Following is the description of task (sensitivities) which has been extracted from a copasi model file. I want to retrieve the information enclosed in **\<problem>** section.

`<Task key="Task_16" name="Sensitivities" type="sensitivities" scheduled="false" updateModel="false">
      <Report reference="Report_3" target="" append="1" confirmOverwrite="0"/>
      <Problem>
        <Parameter name="SubtaskType" type="unsignedInteger" value="1"/>
        <ParameterGroup name="TargetFunctions">
          <Parameter name="SingleObject" type="cn" value="CN=Root,Model=MAPK cascade,Vector=Compartments[compartment],Vector=Metabolites[PP-MAPK],Reference=Concentration"/>
          <Parameter name="ObjectListType" type="unsignedInteger" value="1"/>
        </ParameterGroup>
        <ParameterGroup name="ListOfVariables">
          <ParameterGroup name="Variables">
            <Parameter name="SingleObject" type="cn" value="CN=Root,Model=MAPK cascade,Vector=Reactions[binding of MAPKKK activator],ParameterGroup=Parameters,Parameter=k1,Reference=Value"/>
            <Parameter name="ObjectListType" type="unsignedInteger" value="1"/>
          </ParameterGroup>
          <ParameterGroup name="Variables">
            <Parameter name="SingleObject" type="cn" value=""/>
            <Parameter name="ObjectListType" type="unsignedInteger" value="0"/>
          </ParameterGroup>
        </ParameterGroup>
      </Problem>
      <Method name="Sensitivities Method" type="SensitivitiesMethod">
        <Parameter name="Delta factor" type="unsignedFloat" value="0.001"/>
        <Parameter name="Delta minimum" type="unsignedFloat" value="9.9999999999999998e-13"/>
      </Method>
    </Task>`

I used the function `get_task_settings('Sensitivities', basic_only=False)` with and without setting "basic_only" flag to False, but it gives the same following results: 

`{'scheduled': False, 'update_model': False, 'problem': {'SubtaskType': 1}, 'method': {'Delta factor': 0.001, 'Delta minimum': 1e-12, 'name': 'Sensitivities Method'}, 'report': {'filename': '', 'report_definition': 'Sensitivities', 'append': True, 'confirm_overwrite': True}}`

Here you can see, the above function is returning only the **name** and **value** attributes of the sub-section (\<Parameter >) within the \<Problem> section. 

Can you please suggest how can I retrieve all the required information within **\<Problem>** section?

Thanks

**Comment by fbergmann** [comment]
Indeed, there are no convenience methods for the sensitivities task yet, i'll add it and let you know.

**Comment by hasanbaig** [comment]
Thanks. Looking forward to it.

**Comment by hasanbaig** [comment]
I have updated to release version 0.16. As mentioned in the example, I ran "get_sensitivity_settings()" on the same above model, and got the following results: 

`{'scheduled': False, 
'update_model': False, 
'method': {'Delta factor': 0.001, 'Delta minimum': 1e-12, 'name': 'Sensitivities Method'}, 
'report': {'filename': '', 'report_definition': 'Sensitivities', 'append': True, 'confirm_overwrite': False}, 
'sub_task': 'Steady State', 
'effect': '[PP-MAPK]', 
'cause': 'CN=Root,Model=MAPK cascade,Vector=Reactions[binding of MAPKKK activator],ParameterGroup=Parameters,Parameter=k1,Reference=Value', 
'secondary_cause': 'Not Set'}`

I have the following questions: 

1. I do not understand, where does the sub_task: "Steady State" come from? I do not see any subtask listed in the "Sensitivities" task. 

2. Though I have read the example you have created and I see that you have mentioned briefly about "effect" and "cause" attributes, but I am having hard time correlating these terms with the xml model and I am not able to understand these. Here I see that "cause" is holding a value of only one "cn" attribute values out of the three  **\<ParameterGroup>** sections (see the extracted xml portion of the sensitivity task above). What about other twos? 

Also, need more clarification and correlation of effect. It would be helpful to have a consistency in terminologies with xml model.

**Comment by fbergmann** [comment]
Hello, let me go right to your questions. I've made the implementation, so as to be as close to what you have in the COPASI user interface, there we have: 

![Sensitivities Task](http://copasi.org/Support/User_Manual/Tasks/Sensitivity_Analysis/sensitivities_gui1.png)

So where do these things come from and how can you use them: 

* subtask, currently you have in the xml ` <Parameter name="SubtaskType" type="unsignedInteger" value="1"/>`. In basico you have a class for the subtasks `SENS_ST`, that let you convert between these numbers and the strings. Here, instead of specifying you want to run '1' you are running a `Steady State` analysis
* again, i chose the language that is there in COPASI. the `effect` maps back to what is the `TargetFunctions` element above. However, it can only either be a CN to a specific element, or it can be a list of things. If it is a list of things (say, all non-constant metabolite concentrations, or all initial concentrations), it will be one of the elements from the `SENS` class. While in the XML it looks like they can be set independently from each other, this is not the case. 
* finally to the `cause` and `secondary_cause` elements, those are the items from your `ListOfVariables`. While in theory it would be possible to have more of them, the COPASI user interface only allows access to two of them. 

* as for the CN vs Name thing, when you use basico, you can use CN's all the way to specify the cause / effect elements. Whenever they can be uniquely changed to a name, this is what basico will do, as usually it is easier to type `[X]` than the full CN for the concentration of X. This does not always work out nicely for local parameters unfortunately, that is why right now you see a CN there for it. 

I hope this makes it clearer.

**Comment by hasanbaig** [comment]
Hi Frank,

Thanks a lot. This is really helpful. The reason why I was confused about the terminologies was because I was comparing BasiCO terms with CPS XML format. But you have explained it very well.
