### ISSUE TITLE
set_species failing to set initial concentration

### ISSUE THREAD

**Issue by pmendes** [copasi/basico#28]
I tried this code:
```
add_species('B');
set_species('B', exact=True,  initial_concentration=0.4, status='fixed');

```
and the result is that species 'B' ends up with initial concentration of 1 (default value, set by the add_species), not 0.4 as should have been changed by set_species ...

I had to write:
```
add_species('B', initial_concentration=0.4);
set_species('B', exact=True, status='fixed');
```
to have 'B' actually get the initial concentration of 0.4.

**Comment by pmendes** [comment]
but it turns out that this:
`set_species('en', initial_concentration=0);
`
works as expected, so it may be the issue is when status='fixed' is used together with initial_concentration

**Comment by fbergmann** [comment]
as it turns out, setting the `status` after changing the `initial_concentration` (as is done by set_species) does indeed cause the model to loose the change. A second issue is that the status change does not immediately work as i would have expected. I'll get a version out later, that will fix this, so all that is needed would be one line: 

```python
add_species('B', initial_concentration=0.4, status='fixed');
```

thanks for letting me know.

**Comment by fbergmann** [comment]
i've made a new release (0.37) that is now available on pypi that resolves this issue.
