### ISSUE TITLE
Clarification around Parameter Estimation Variables

### ISSUE THREAD

**Issue by Theo-BRN** [copasi/basico#46]
Hey Frank,

I noticed that `plot per experiment` doesn't seem to return the current fit, if, `randomize_start_values` was set to True in the last `run_parameter_estimation`.

Additionally I was getting a bit confused with the rationale behind parameters 'storage' in parameter estimation, and I wondered if you could clarify some assumptions for me. 

- After running a simulation, is the solution stored in some kind of PE object, or just the output of the function itself?
- Does the 'update_model' function argument, update the qlobal quantities or update the PE object with the solution?
    - It seems my model parameters change even though `update_model` is set to False
- My overall assumption would be that some kind of PE object or class instance stores the solution to parameter estimation runs. And when setting `update_model` to True, you effectively run `set_parameters(...)` for those particular parameters, changing the global quantities to the solution parameters.

Thanks for any help you can offer with this! Hope you're doing well :-)

Best, 
Theo

**Comment by fbergmann** [comment]
Thanks for filing this issue let me get to the points in turn

* the one thing for basico to change is clearly, that the plot functions (or rather `get_current_solution`) clearly needs to temporarily disable `randomize_start_values`. Because of the randomization, you are likely to hit an infeasible solution which results in you not getting a simulation result. 

as to your questions about storage. All tasks in COPASI just modify the current models state. If `update_model=False`, then the **initial state** remains the same, and the task is just modifying the **transient state**. If `update_model` is true, then the final transient state becomes the new **initial state*. 

so for this issue i'll change basico, to not randomize values for the current result ever, which will solve the issue you were having with plots.

**Comment by fbergmann** [comment]
I have released a new basico version, that ensures that `get_simulation_resutls` no longer uses random start values.
